In [1]:
import numpy as np 
a = np.array([[2, 5],
              [1, 5]])
b = np.array([[5, 3],
              [3, 2]])
print("Array1:") 
print(a)
print("Array2:") 
print(b)
print("\nMultiply said arrays of same size element-by-element:")
print(np.multiply(a, b))

Array1:
[[2 5]
 [1 5]]
Array2:
[[5 3]
 [3 2]]

Multiply said arrays of same size element-by-element:
[[10 15]
 [ 3 10]]
