In [2]:

import numpy as np  
a = int(input("Enter the number of rows:"))
b = int(input("Enter the number of columns:"))  
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
mat = np.matrix(entries).reshape(a, b)
print(mat)
print("Original matrix:")
print(mat)
result =  np.linalg.inv(mat)
print("Inverse of the said matrix:")
print(result)


Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
2 3 4 5
[[2 3]
 [4 5]]
Original matrix:
[[2 3]
 [4 5]]
Inverse of the said matrix:
[[-2.5  1.5]
 [ 2.  -1. ]]
