In [2]:
import numpy as np
nums1 = np.array([5, 1, 8])
nums2 = np.array([49, 1, 2])
np.set_printoptions(precision=15)
print("Original arrays:")
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(nums1 == nums2)
nums1 = np.array([5, 1.5, 0.23])
nums2 = np.array([4, 1.501, 0.23])
print("\nOriginal arrays:")
np.set_printoptions(precision=15)
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(np.equal(nums1, nums2))

Original arrays:
[5 1 8]
[49  1  2]

Test said two arrays are equal (element wise) or not:?
[False  True False]

Original arrays:
[5.   1.5  0.23]
[4.    1.501 0.23 ]

Test said two arrays are equal (element wise) or not:?
[False False  True]
